//Login action types
export const RETRIEVE_TWEETS_REQUEST="RETRIEVE_TWEETS_REQUEST";
export const RETRIEVE_TWEETS_SUCCESS="RETRIEVE_TWEETS_SUCCESS";
export const RETRIEVE_TWEETS_FAILURE = "RETRIEVE_TWEETS_FAILURE";

export const DELETE_TWEET_REQUEST = "DELETE_TWEET_REQUEST";
export const DELETE_TWEET_SUCCESS = "DELETE_TWEET_SUCCESS";
export const DELETE_TWEET_FAILURE="DELETE_TWEET_FAILURE";

export const UPDATE_TWEET_REQUEST = "UPDATE_TWEET_REQUEST";
export const UPDATE_TWEET_SUCCESS = "UPDATE_TWEET_SUCCESS";
export const UPDATE_TWEET_FAILURE = "UPDATE_TWEET_FAILURE";

export const ADD_TAG="ADD_TAG";

